// resources/js/Components/ActionLink.tsx
import React from 'react';
import { Link } from '@inertiajs/react';
import { cn } from '@/lib/utils';

interface ActionLinkProps {
    href: string;
    className?: string;
    children: React.ReactNode;
}

export default function ActionLink({ href, className, children }: ActionLinkProps) {
    return (
        <Link
            href={href}
            className={cn(
                "inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring focus:ring-gray-300 disabled:opacity-25 transition",
                className
            )}
        >
            {children}
        </Link>
    );
}

// resources/js/Components/ActionLink.vue
<script setup>
defineProps({
    href: String
});
</script>

<template>
    <a :href="href"
       class="inline-flex items-center px-4 py-2 bg-white border border-gray-800 rounded-md font-semibold text-xs text-gray-800 uppercase tracking-widest hover:bg-gray-200 hover:border-gray-600 active:border-gray-900 focus:outline-hidden focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
        <slot></slot>
    </a>
</template>
