// resources/js/Components/Socialstream.tsx
import React from 'react';

// Import components - adjust paths as needed
import InputError from '@/Components/InputError';
import ProviderIcon from '@/Components/SocialstreamIcons/ProviderIcon';
import { Button } from '@/Components/ui/button';

interface Provider {
    id: string;
    name: string;
    buttonLabel?: string;
}

interface SocialLoginProps {
    prompt?: string;
    error?: string | null;
    providers?: Provider[];
    labels?: Record<string, string>;
}

const SocialLogin: React.FC<SocialLoginProps> = ({ prompt = 'Or Login Via', error = null, providers = [], labels }) => {
    const handleProviderClick = (providerId: string) => {
        // Adjust this based on your routing solution
        // This assumes you have a similar route helper available
        window.location.href = (window as any).route('oauth.redirect', { provider: providerId });
    };

    if (!providers || providers.length === 0) {
        return null;
    }

    return (
        <div className="mt-6 mb-2 space-y-6">
            <div className="relative text-center text-sm after:absolute after:inset-0 after:top-1/2 after:z-0 after:flex after:items-center after:border-t after:border-border">
                <span className="relative z-10 bg-background px-2 text-muted-foreground">Or continue with</span>
            </div>

            {error && (
                <div className="text-center">
                    <InputError message={error} />
                </div>
            )}

            <div className="grid gap-4">
                {providers.map((provider) => (
                    <Button key={provider.id} variant="outline" onClick={() => handleProviderClick(provider.id)} className="flex items-center">
                        <ProviderIcon provider={provider} classes="h-6 w-6" />
                        <span className="text-sm font-medium">{provider.buttonLabel || provider.name}</span>
                    </Button>
                ))}
            </div>
        </div>
    );
};

export default SocialLogin;

// resources/js/Components/Socialstream.vue
<script setup>
import InputError from '@/Components/InputError.vue';
import ProviderIcon from '@/Components/SocialstreamIcons/ProviderIcon.vue';

defineProps({
    prompt: {
        type: String,
        default: 'Or Login Via',
    },
    error: {
        type: String,
        default: null,
    },
    providers: {
        type: Array,
    },
    labels: {
        type: Object,
    }
});
</script>

<template>
    <div v-if="providers.length" class="space-y-6 mt-6 mb-2">
        <div class="relative flex items-center">
            <div class="grow border-t border-gray-400"></div>
            <span class="shrink text-gray-400 px-6">
                {{ prompt }}
             </span>
            <div class="grow border-t border-gray-400"></div>
        </div>

        <InputError v-if="error" :message="error" class="text-center"/>

        <div class="grid gap-4">
            <a v-for="provider in providers" :key="provider.id"
               class="flex gap-2 items-center justify-center transition duration-200 border border-gray-400 w-full py-2.5 rounded-lg text-sm shadow-xs hover:shadow-md font-normal text-center inline-block"
               :href="route('oauth.redirect', provider.id)">
                <ProviderIcon :provider="provider" classes="h-6 w-6 mx-2"/>
                <span class="block font-medium text-sm text-gray-700">{{ provider.buttonLabel || provider.name }}</span>
            </a>
        </div>
    </div>
</template>
