// resources/js/Pages/Auth/Login.tsx
import AuthenticationCard from '@/Components/AuthenticationCard';
import InputError from '@/Components/InputError';
import Socialstream from '@/Components/Socialstream';
import { Head, useForm } from '@inertiajs/react';
import React from 'react';

import { Button } from '@/Components/ui/button';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';

interface Props {
    canResetPassword?: boolean;
    status?: string;
    errors?: {
        email?: string;
        password?: string;
        socialstream?: string;
    };
    socialstream?: {
        show?: boolean;
        providers?: any[];
        prompt?: string;
        labels?: Record<string, string>;
    };
}

const Login: React.FC<Props> = ({ canResetPassword, status, errors = {}, socialstream }) => {
    const form = useForm({
        email: '',
        password: '',
        remember: true,
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();

        form.transform((data) => ({
            ...data,
            remember: data.remember ? 'on' : '',
        }));
        
        form.post(route('login'), {
            onFinish: () => form.reset('password'),
        });
    };

    return (
        <>
            <Head title="Log in" />

            <AuthenticationCard Title="Log in to your account" Description="Enter your email and password below to log in">
                {status && <div className="mb-4 text-sm font-medium text-green-600">{status}</div>}

                <form onSubmit={handleSubmit} className="grid gap-4">
                    <div className="grid gap-2">
                        <Label htmlFor="email">Email</Label>
                        <Input
                            id="email"
                            value={form.data.email}
                            onChange={(e) => form.setData('email', e.target.value)}
                            type="email"
                            placeholder="m@example.com"
                            required
                            autoFocus
                        />
                        <InputError message={form.errors.email} />
                    </div>

                    <div className="grid gap-2">
                        <div className="flex items-center">
                            <Label htmlFor="password">Password</Label>
                            {canResetPassword && (
                                <a href={route('password.request')} className="ml-auto inline-block text-sm underline">
                                    Forgot your password?
                                </a>
                            )}
                        </div>
                        <Input
                            id="password"
                            value={form.data.password}
                            onChange={(e) => form.setData('password', e.target.value)}
                            type="password"
                            autoComplete="current-password"
                            required
                        />
                        <InputError message={form.errors.password} />
                    </div>

                    <Button type="submit" className={`w-full ${form.processing ? 'opacity-50' : ''}`} disabled={form.processing}>
                        {form.processing ? 'Logging in...' : 'Login'}
                    </Button>
                </form>

                {socialstream?.show && socialstream?.providers?.length && (
                    <Socialstream
                        error={errors?.socialstream}
                        prompt={socialstream?.prompt || 'Or Login Via'}
                        labels={socialstream?.labels || {}}
                        providers={socialstream?.providers || []}
                    />
                )}

                <div className="mt-4 text-center text-sm">
                    Don't have an account?{' '}
                    <a href="/register" className="underline">
                        Sign up
                    </a>
                </div>
            </AuthenticationCard>
        </>
    );
};

export default Login;

// resources/js/Pages/Auth/Login.vue
<script setup>
import {Head, Link, useForm} from '@inertiajs/vue3';
import AuthenticationCard from '@/Components/AuthenticationCard.vue';
import AuthenticationCardLogo from '@/Components/AuthenticationCardLogo.vue';
import Checkbox from '@/Components/Checkbox.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import Socialstream from '@/Components/Socialstream.vue';
import TextInput from '@/Components/TextInput.vue';

defineProps({
    canResetPassword: Boolean,
    status: String,
});

const form = useForm({
    email: '',
    password: '',
    remember: false,
});

const submit = () => {
    form.transform(data => ({
        ...data,
        remember: form.remember ? 'on' : '',
    })).post(route('login'), {
        onFinish: () => form.reset('password'),
    });
};
</script>

<template>
    <Head title="Log in"/>

    <AuthenticationCard>
        <template #logo>
            <AuthenticationCardLogo/>
        </template>

        <div v-if="status" class="mb-4 font-medium text-sm text-green-600">
            {{ status }}
        </div>

        <form @submit.prevent="submit">
            <div>
                <InputLabel for="email" value="Email"/>
                <TextInput
                    id="email"
                    v-model="form.email"
                    autofocus
                    class="mt-1 block w-full"
                    required
                    type="email"
                />
                <InputError :message="form.errors.email" class="mt-2"/>
            </div>

            <div class="mt-4">
                <InputLabel for="password" value="Password"/>
                <TextInput
                    id="password"
                    v-model="form.password"
                    autocomplete="current-password"
                    class="mt-1 block w-full"
                    required
                    type="password"
                />
                <InputError :message="form.errors.password" class="mt-2"/>
            </div>

            <div class="block mt-4">
                <label class="flex items-center">
                    <Checkbox v-model:checked="form.remember" name="remember"/>
                    <span class="ml-2 text-sm text-gray-600">Remember me</span>
                </label>
            </div>

            <div class="flex items-center justify-end mt-4">
                <Link v-if="canResetPassword" :href="route('password.request')"
                      class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-hidden focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Forgot your password?
                </Link>

                <PrimaryButton :class="{ 'opacity-25': form.processing }" :disabled="form.processing" class="ml-4">
                    Log in
                </PrimaryButton>
            </div>
        </form>

        <Socialstream v-if="$page.props.socialstream.show && $page.props.socialstream.providers.length"
                      :error="$page.props?.errors?.socialstream || null" :prompt="$page.props.socialstream.prompt"
                      :labels="$page.props.socialstream.labels" :providers="$page.props.socialstream.providers"/>
    </AuthenticationCard>
</template>
